/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.complaintmanagementsystem;

import com.mycompany.complaintmanagementsystem.Query.User;
import static com.mycompany.complaintmanagementsystem.Query.currentAdmin;
import javax.swing.JOptionPane;
/**
 *
 * @author tushar sharma
 */

public class ComplaintManagementSystem extends javax.swing.JFrame {

    /**
     * Creates new form ComplaintManagementSystem
     */
    public ComplaintManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tbdLoginpanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblUserpass = new javax.swing.JLabel();
        txtUsernamefield = new javax.swing.JTextField();
        btnUsersubmit = new javax.swing.JButton();
        pwdUserpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAdminname = new javax.swing.JLabel();
        lblUserpass1 = new javax.swing.JLabel();
        txtAdminnamefield = new javax.swing.JTextField();
        btnAdminsubmit = new javax.swing.JButton();
        pwdAdminpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Complaint System");
        setBackground(new java.awt.Color(255, 255, 255));

        tbdLoginpanel.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("Username :");

        lblUserpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserpass.setText("Password :");

        txtUsernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernamefieldActionPerformed(evt);
            }
        });

        btnUsersubmit.setBackground(new java.awt.Color(255, 204, 255));
        btnUsersubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUsersubmit.setForeground(new java.awt.Color(255, 0, 0));
        btnUsersubmit.setText("Submit");
        btnUsersubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersubmitActionPerformed(evt);
            }
        });

        pwdUserpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdUserpassActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SHRI MATA VAISHNO DEVI UNIVERSITY");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\tushar sharma\\Documents\\NetBeansProjects\\ComplaintManagementSystem\\src\\main\\java\\com\\mycompany\\complaintmanagementsystem\\smvdu_logo.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(lblUserpass, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUsernamefield)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUsersubmit)
                                .addGap(71, 71, 71))
                            .addComponent(pwdUserpass, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(152, 175, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserpass)
                    .addComponent(pwdUserpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnUsersubmit)
                .addGap(15, 15, 15))
        );

        tbdLoginpanel.addTab("user", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        lblAdminname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAdminname.setText("Admin :");

        lblUserpass1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserpass1.setText("Password :");

        txtAdminnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminnamefieldActionPerformed(evt);
            }
        });

        btnAdminsubmit.setBackground(new java.awt.Color(255, 204, 255));
        btnAdminsubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdminsubmit.setForeground(new java.awt.Color(255, 0, 0));
        btnAdminsubmit.setText("Submit");
        btnAdminsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsubmitActionPerformed(evt);
            }
        });

        pwdAdminpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdAdminpassActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SHRI MATA VAISHNO DEVI UNIVERSITY");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\tushar sharma\\Documents\\NetBeansProjects\\ComplaintManagementSystem\\src\\main\\java\\com\\mycompany\\complaintmanagementsystem\\smvdu_logo.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAdminname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserpass1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdAdminpass, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdminnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdminsubmit))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdAdminpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserpass1))
                .addGap(37, 37, 37)
                .addComponent(btnAdminsubmit)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        tbdLoginpanel.addTab("admin", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdLoginpanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdLoginpanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernamefieldActionPerformed

    private void btnUsersubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersubmitActionPerformed
        // TODO add your handling code here:
        String username = txtUsernamefield.getText();
        String password = pwdUserpass.getText();
        
          try {
        // Call the UserLogin method and get the User object
        User currentUser = (User) Query.UserLogin(username, password);
        
        if (currentUser != null) {
            // Login successful
            JOptionPane.showMessageDialog(rootPane, "Login success!");

            // Now you can pass the User object to the MainApplication frame
            new MainApplication(currentUser).setVisible(true);

            // Close the current login window
            this.dispose();
        } else {
            // Invalid credentials
            JOptionPane.showMessageDialog(rootPane, "Invalid credentials!");
        }
    } catch (Exception e) {
        System.out.println("Error in logging in: " + e.getMessage());
    }
    }//GEN-LAST:event_btnUsersubmitActionPerformed

    private void txtAdminnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminnamefieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAdminnamefieldActionPerformed

    private void btnAdminsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsubmitActionPerformed
        String adminname = txtAdminnamefield.getText();
        String password = pwdAdminpass.getText();
        
          try {
        // Call the adminLogin method and get the User object
        User currentUser = (User) Query.UserLogin(adminname, password);
        
        if (currentAdmin != null) {
            // Login successful
            JOptionPane.showMessageDialog(rootPane, "Login success!");

            // Now you can pass the Admin object to the MainApplication frame
            new AdminPanel(currentAdmin).setVisible(true);

            // Close the current login window
            this.dispose();
        } else {
            // Invalid credentials
            JOptionPane.showMessageDialog(rootPane, "Invalid credentials!");
        }
    } catch (Exception e) {
        System.out.println("Error in logging in: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAdminsubmitActionPerformed

    private void pwdAdminpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdAdminpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdAdminpassActionPerformed

    private void pwdUserpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdUserpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdUserpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplaintManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplaintManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplaintManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplaintManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ComplaintManagementSystem().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminsubmit;
    private javax.swing.JButton btnUsersubmit;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdminname;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUserpass;
    private javax.swing.JLabel lblUserpass1;
    private javax.swing.JPasswordField pwdAdminpass;
    private javax.swing.JPasswordField pwdUserpass;
    private javax.swing.JTabbedPane tbdLoginpanel;
    private javax.swing.JTextField txtAdminnamefield;
    private javax.swing.JTextField txtUsernamefield;
    // End of variables declaration//GEN-END:variables
    
}
